### ISSUE TITLE
[Bug]user login failed and receive authenticate failure error message

### ISSUE THREAD

**Issue by dashenstone** [flowerfine/scaleph#147]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

master

### What happened

![image](https://user-images.githubusercontent.com/43053584/180341320-45270dd8-88a2-487e-af99-bc7fbef0120e.png)

### Error Exception

```log
errorCode: "401"
errorMessage: "用户认证不通过！"
showType: 4
success: false
```

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gleiyu** [comment]
@jczk please describe  the problem in detail

**Comment by dashenstone** [comment]
1、cd scaleph-ui
      npm install --location=global @angular/cli
      npm install --force
2、cd scaleph
      mvn clean package -DskipTests
3、nginx setting
4、java -jar scaleph-api.jar
5、http://IP/login
      sys_admin/123456
6、方便微信、QQ、钉钉、邮箱联系吗

**Comment by gleiyu** [comment]
I think it might be the nginx setting , you can contact me by email or wechat
wechat  gleiyu
email gleiyu@sina.cn

**Comment by dashenstone** [comment]
nginx 配置也是参考如下配置的：https://github.com/flowerfine/scaleph/blob/dev/docs/build/build.md#nginx-setting详情见附件

----- 原始邮件 -----
发件人：gleiyu ***@***.***>
收件人：flowerfine/scaleph ***@***.***>
抄送人：jczk ***@***.***>,  Mention ***@***.***>
主题：Re: [flowerfine/scaleph] [Bug]user login failed and receive authenticate failure error message (Issue #147)
日期：2022年07月22日 10点01分


@jczk please describe  the problem in detail

**Comment by dashenstone** [comment]
![image](https://user-images.githubusercontent.com/43053584/180738497-1b3dfbe8-f4eb-4da1-89a3-40e4cc5dc9a8.png)
