### ISSUE TITLE
[Bug][docker]login need provide a code/Verification Code

### ISSUE THREAD

**Issue by imx7** [flowerfine/scaleph#151]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

登录需要验证码

### Screenshots

![image](https://user-images.githubusercontent.com/10492097/180630504-bc31451d-d627-4657-a241-a6969d43a763.png)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
Have you verified that scaleph-api container start completelly?
Because the login page will request backend server to generate captcha, if scaleph-api start fails, then login page can't show the captcha successfully.

I had bootstraped scaleph through [deploy on docker](https://github.com/flowerfine/scaleph/blob/dev/docs/deploy/docker/docker.md) successfully, can you provide more details about that how you bootstrap scaleph?
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/24804318/180636639-5b9e6c62-8dd7-4c5e-957f-284dc72ad552.png">

**Comment by imx7** [comment]
os:win10 pro
wsl:ubuntu 20.04.
![image](https://user-images.githubusercontent.com/10492097/180637648-2846bfa9-e8da-432c-9627-5a41116909b7.png)
![image](https://user-images.githubusercontent.com/10492097/180637668-5d0925b3-3a88-46c6-8e8a-ea10ab3991ad.png)
![image](https://user-images.githubusercontent.com/10492097/180637703-c278a516-7807-4216-ac1f-9ccb0ae695d4.png)
![image](https://user-images.githubusercontent.com/10492097/180637712-01012847-7b19-4451-8caa-e8a4dbb4a12b.png)
![image](https://user-images.githubusercontent.com/10492097/180637720-bf5a1037-7fac-48a1-b601-55b8196aa9c1.png)
**docker logs scaleph-ui**
user nginx;

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    client_max_body_size 5g;

    keepalive_timeout  65;

    upstream backend {
        server  "scaleph-api:8080";
    }
    server {
        listen       80;
        server_name  localhost;

        underscores_in_headers on;

        location / {
            root   /dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api {
             proxy_pass  http://backend/scaleph/api;
             proxy_redirect  default;
        }
    }
}
2022/07/24 07:47:04 [emerg] 10#10: host not found in upstream "scaleph-api:8080" in /etc/nginx/nginx.conf:20
nginx: [emerg] host not found in upstream "scaleph-api:8080" in /etc/nginx/nginx.conf:20
user nginx;

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    client_max_body_size 5g;

    keepalive_timeout  65;

    upstream backend {
        server  "scaleph-api:8080";
    }
    server {
        listen       80;
        server_name  localhost;

        underscores_in_headers on;

        location / {
            root   /dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api {
             proxy_pass  http://backend/scaleph/api;
             proxy_redirect  default;
        }
    }
}
172.27.0.1 - - [24/Jul/2022:07:48:23 +0000] "GET /login HTTP/1.1" 200 544 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62"
172.27.0.1 - - [24/Jul/2022:07:48:23 +0000] "GET /styles.css.map HTTP/1.1" 200 293482 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62"
172.27.0.1 - - [24/Jul/2022:07:48:23 +0000] "GET /api/authCode?d=1658648900372 HTTP/1.1" 502 559 "http://localhost/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62"
2022/07/24 07:48:23 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /api/authCode?d=1658648900372 HTTP/1.1", upstream: "http://172.27.0.5:8080/scaleph/api/authCode?d=1658648900372", host: "localhost", referrer: "http://localhost/login"

**Comment by kalencaya** [comment]
Thanks for your help.
From provided log, we can figure that scaleph-api start fails and scaleph-ui request refuesed by scaleph-api.
```
2022/07/24 07:48:23 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /api/authCode?d=1658648900372 HTTP/1.1", upstream: "http://172.27.0.5:8080/scaleph/api/authCode?d=1658648900372", host: "localhost", referrer: "http://localhost/login"
```
`tools/docker/deploy/scaleph/docker-compose.yml` has a defect which scaleph-api service depends on mysql but doesn't  check mysql health status, so if you use `docker compose up` command and wait for a moment,  scaleph-api log will output another restart attempt log.

<img width="1642" alt="image" src="https://user-images.githubusercontent.com/24804318/180639632-0bf1353d-27c3-4e74-b868-b7b1b8ecd844.png">

After scaleph-api restarts successfully, the login page will show captcha properly.

**Comment by kalencaya** [comment]
Pull the lateset source code and try again.
If any exception exists, never hesitate to reply this issue.

**Comment by imx7** [comment]
ok，3Q
