### ISSUE TITLE
[Bug] [scaleph-ui] jdbc sink config incorrect

### ISSUE THREAD

**Issue by lizu18xz** [flowerfine/scaleph#156]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

Test  task Kafka to JDBC ,   Incorrect page parameters:

"sink" : [
        {
            "url" : "jdbc:mysql://localhost:3306/testdata?",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "username" : "root",
            "password" : "123456",
            "query" : "insert into test02 (id,name) values(?, ?)",
            **"batchSize" : "2",**
            "plugin_name" : "JdbcSink",
            "_node_type" : "sink",
            "_node_id" : 12,
            "source_table_name" : "table_13"
        }

 In  Seatunnel    project Parameter is :
 public static final String SINK_BATCH_SIZE = "batch_size";

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
We will check and handle it as soon as possible, or you can try to fix it and contribute to scaleph

**Comment by lizu18xz** [comment]
I tried to fix and contribute, I don't know whether the process is standardized
