### ISSUE TITLE
[Bug] [Module Name] edit dataSource bug

### ISSUE THREAD

**Issue by lizu18xz** [flowerfine/scaleph#186]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

Just click OK，No password changed,but meta_datasource table  props change
![image](https://user-images.githubusercontent.com/20568293/184577667-c7138b17-b500-492e-be4a-51538192ceb1.png)

![image](https://user-images.githubusercontent.com/20568293/184577465-725bf90a-39ea-4be8-81b8-a0a66f8619b1.png)

![image](https://user-images.githubusercontent.com/20568293/184577485-2d020825-8f2f-4505-ab7c-c147e9780455.png)

![image](https://user-images.githubusercontent.com/20568293/184577494-f77191c4-c44a-4015-8226-e48bf7f3e010.png)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
see this question @gleiyu

**Comment by gleiyu** [comment]
i will fix this bug soon
