### ISSUE TITLE
[Bug] [workflow] trans plugin not work

### ISSUE THREAD

**Issue by hx23840** [flowerfine/scaleph#212]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

docker compose latest

### What happened

add trans plugin,it's display nothing

### Screenshots

![Screenshot from 2022-08-27 10-53-59](https://user-images.githubusercontent.com/42536066/187011617-d1cfe704-d718-4609-8ea9-094d969ed13b.png)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
Sorry for misleading, actually transform and process menu all operators are not available, even some source and sink operators don't work.

Scaleph all source, sink and transform base on seatunnel, transform connector is rare and some source and sink connectors have few bugs which already fixed on newer version.

Luckily, seatunnel is incubating v2 version connectors and scaleph will start to switch  to v2 connectors from next week, which will consume us one month. It is not bad for people join this process

**Comment by hx23840** [comment]
> Sorry for misleading, actually transform and process menu all operators are not available, even some source and sink operators don't work.
> 
> Scaleph all source, sink and transform base on seatunnel, transform connector is rare and some source and sink connectors have few bugs which already fixed on newer version.
> 
> Luckily, seatunnel is incubating v2 version connectors and scaleph will start to switch to v2 connectors from next week, which will consume us one month. It is not bad for people join this process

thx,looking forward to realization
