### ISSUE TITLE
[Bug] [scaleph-ui-react] function hasPrivilege json parse error

### ISSUE THREAD

**Issue by hx23840** [flowerfine/scaleph#219]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

dev

### What happened

if user first login,function hasPrivilege of auth.ts json parse error

### Screenshots

![Screenshot from 2022-08-31 11-11-02](https://user-images.githubusercontent.com/42536066/187584339-336c3397-ce19-496a-99ae-c62fb0432f20.png)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
Yesterday, I had encountered page redirect to login page failure and I had to join `/login` path to the url and refresh auth code manually, then login success and web work well.

**Comment by hx23840** [comment]
> Yesterday, I had encountered page redirect to login page failure and I had to join `/login` path to the url and refresh auth code manually, then login success and web work well.

Yes, you can skip this error, because this skip the check function, it's also a bug. but if you fix the json parse code, it can auto redirect login page
