### ISSUE TITLE
[Bug][deploy]docker-compose up 

### ISSUE THREAD

**Issue by luckymlog** [flowerfine/scaleph#225]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

docker-compose up
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
Pulling scaleph-api (ghcr.io/flowerfine/scaleph/scaleph-api:0.0.1)...
ERROR: manifest unknown

### Description

docker-compose up
WARNING: The following deploy sub-keys are not supported and have been ignored: resources.reservations.cpus
Pulling scaleph-api (ghcr.io/flowerfine/scaleph/scaleph-api:0.0.1)...
ERROR: manifest unknown

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/24804318/188269388-eae6e197-5058-4a85-8b36-29fc981cc6f9.png">
When scaleph released 0.0.1, it had changed tag name to `v0.0.1` and didn't fix `scaleph-api` and `scaleph-ui` image tag. You have to change tag name to `v0.0.1` on `docker-compose.yml`
