### ISSUE TITLE
建议：能否以安装包的方式进行安装

### ISSUE THREAD

**Issue by 18772247265** [flowerfine/scaleph#469]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

发现这个项目是因为seatunnel，但是它没有web操作界面，然后网上查找发现了这个项目的介绍，看到了零星的界面截图，感觉很好，但是在准备下载使用的过程中碰壁很多。

### Description

我本人是数据开发工程师，java懂一点，不多，docker基本不怎么了解，百度了很久，在docker下载镜像的过程中遇到了不少的问题，下载不下来，无法正常安装使用，提两点建议，不知道是否合理：

1、能否提供压缩包或者什么其他方式，下载后解压后直接通过命令start或者什么命令就能启动（这样是否更简易）

2、有没有社区用户群（钉钉或者微信）供使用者一起探讨

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by sszc** [comment]
确实，我们也需要使用安装包的方式。因为在线上环境没有连接外网，在使用docker部署时下载镜像是个难题。

**Comment by LiuBodong** [comment]
I'll do this later. But maybe need some time ...

**Comment by 18772247265** [comment]
Thank you. I look forward to it
