### ISSUE TITLE
seatunnel-flink The jvm parameters do not take effect

### ISSUE THREAD

**Issue by aokunsang** [flowerfine/scaleph#498]
`configuration.setString(CoreOptions.FLINK_JVM_OPTIONS, "-Dflink_job_name=seatunneljob");`

Adding this line to the doSubmitSeatunnel() method will not get the value correctly in flink's log4j.properties with ${sys:flink_job_name}. 
Guess it wasn't passed on.

**Comment by aokunsang** [comment]
After following the code, flinkful doesn't seem to support this?   Ask for advice

**Comment by kalencaya** [comment]
checkout how flink handles `CoreOptions.FLINK_JVM_OPTIONS` option

**Comment by aokunsang** [comment]
I'm sorry. This is my fault. `CoreOptions.FLINK_JVM_OPTIONS` in flink1.13.6 means: Java options to start the JVM of all Flink processes with.
So, it only works in application or per-job mode.
