### ISSUE TITLE
[Feature][scaleph-sql-template] add flink sql template jar and flink sql image

### ISSUE THREAD

**Issue by kalencaya** [flowerfine/scaleph#530]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

There are two ways for submitting flink sql job, one is template jar such as [sql-runner](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java), other is sql gateway which submits JobGraph directly.
Template jar is an easily way to support flink sql job and scaleph wants to implement this firstly.

### Description

There are two tasks or stages:

- [ ] add a `scaleph-engine`/`scaleph-sql-template` module and implement the template main class such as [sql-runner](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java).
- [ ] add template sql docker image which names `scaleph/scaleph-sql-template-${flinkversion}-${jdkversion}` such as [Dockerfile](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/Dockerfile).

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by LiuBodong** [comment]
OK
