### ISSUE TITLE
[Bug] [kubernetes template] 不能新建template

### ISSUE THREAD

**Issue by Pandas886** [flowerfine/scaleph#658]
### Already searched before asking?

- [X] I had searched in the [issues](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scaleph Version or Branch

本地拉取使用最新代码用docker compose方式启动

### What happened

![image](https://github.com/flowerfine/scaleph/assets/123344357/ed10365a-6849-41cb-aa18-7be2936f0056)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
I'll complete it recently two days and release it on 2.0.1 version
